# Generated by Django 5.2.8 on 2026-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('symptoms', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('completed', 'Completed')], default='waiting', max_length=20)),
            ],
        ),
    ]
