# Generated by Django 5.2.8 on 2026-06-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0002_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_treatment', 'In Treatment'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='waiting', max_length=20),
        ),
    ]
