# Generated by Django 5.2.8 on 2026-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0005_alter_patient_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='severity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')]),
        ),
    ]
