# Generated by Django 5.2.8 on 2026-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0006_alter_patient_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('total_count', models.IntegerField()),
                ('available_count', models.IntegerField()),
            ],
        ),
    ]
