# Generated by Django 5.2.8 on 2026-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0007_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('availability', models.IntegerField()),
            ],
        ),
    ]
