# Generated by Django 5.2.8 on 2026-06-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0009_specialization_alter_doctor_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='specialization_link',
        ),
    ]
