# Generated by Django 5.2.8 on 2026-06-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ertracker', '0010_rename_specialization_doctor_specialization_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization_link',
            new_name='specialization',
        ),
    ]
